name: Deploy to WikiTree Apps

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
      env:
        VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        VITE_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    - name: Install lftp
      run: sudo apt-get install -y lftp
    - name: Set up ssh
      run: |
        mkdir ~/.ssh
        echo 'apps-sftp.wikitree.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFr/n45SqtcLL2xou61C6UdmSeCYrQ01UlvS7ZzleFOD' >> ~/.ssh/known_hosts
    - run: npm run deploy-wikitree
      env:
        LFTP_PASSWORD: ${{ secrets.WIKITREE_PASSWORD }}
